motd=Linggango RPG - Forge 1.20.1
level-name=world
gamemode=survival
difficulty=hard
allow-cheats=false
pvp=true
online-mode=true
enable-command-block=true
view-distance=8
simulation-distance=6
max-players=10
server-port=25565
enable-status=true
spawn-protection=0
sync-chunk-writes=false
